# Generated by Django 4.1.6 on 2023-02-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_logo_portifolio_delete_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
