# Generated by Django 4.1.6 on 2023-02-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portifolio',
            name='color',
        ),
        migrations.DeleteModel(
            name='color',
        ),
    ]
