# Generated by Django 4.1.5 on 2023-02-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_portifolio_color_delete_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portifolio',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portifolio',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='portifolio',
            name='size',
        ),
        migrations.RemoveField(
            model_name='portifolio',
            name='status',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='logo',
        ),
        migrations.DeleteModel(
            name='size',
        ),
    ]
