# Generated by Django 4.1.6 on 2023-02-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_post_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolio',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
